version: '2'

services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8080:8080
        restart: always

    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always

    apache:
        depends_on:
            - reverseproxy
        image: httpd:alpine
        restart: always

    apione:
        depends_on: 
            - reverseproxy
        image: apione
        restart: always

    apitwo:
        depends_on: 
            - reverseproxy
        image: apitwo
        restart: always